[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"]}
tokio = { version = "1.50.0", features = ["full"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
thiserror = "2.0.18"
filetime = "0.2.27"
temp-dir = "0.2.0"
log = "0.4.29"
validator = { version = "0.20", features = ["derive"] }
bon = "3.9.1"
regex = "1.12.3"
tracing = "0.1.44"
jpeg-encoder = "0.7.0"
serde_json = "1.0.149"
serde = "1.0.228"
rand = "0.10.0"
mmap-sync = "2.0.1"
rkyv = "0.7.40"
bytecheck = { version = "~0.6.8", default-features = false }
tower = "0.5.3"
tracing-subscriber = { version = "0.3.23", features = ["std", "env-filter", "ansi"] }
dotenv = "0.15.0"
metrics = "0.24.3"
metrics-exporter-otel = "0.3.0"
opentelemetry_sdk = "0.31.0"
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31", default-features = false, features = ["reqwest-blocking-client", "http-proto", "trace", "metrics", "logs", "internal-logs"] }
uuid = { version = "1.23.0", features = ["v4"] }
figment = "0.10.19"
url = { version = "2.5.8", features = ["serde"] }
opentelemetry-appender-tracing = "0.31.1"
reqwest = "0.13.2"
